branches:
  only:
    - master

language: android
sudo: false
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=26
    - ANDROID_EMULATOR_LEVEL=26
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ADB_INSTALL_TIMEOUT=5

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - nvm install v7.10.0

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-${ANDROID_BUILD_TOOLS_VERSION}
    - android-${ANDROID_API_LEVEL}
    - sys-img-armeabi-v7a-addon-google_apis-google-26

before_script:
  - android list targets
  - echo ANDROID_EMULATOR_LEVEL=${ANDROID_EMULATOR_LEVEL}
  - echo ANDROID_EMULATOR_LEVEL="${ANDROID_EMULATOR_LEVEL}"
  - echo ANDROID_EMULATOR_LEVEL="${ANDROID_ABI}"
  - echo no | android create avd --force --name test --target android-26 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - npm install -g appium
  - appium &

script:
  - ./gradlew clean check --info
